name: tremsolapp
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publication to pub.dev

#version: 1.0.1+1
version: 1.0.2+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.4.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.1.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.3
  flutter_staggered_grid_view: ^0.6.2
  video_player: ^2.9.2
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  pay_with_paystack: ^1.0.10
  intl: ^0.19.0
  google_sign_in: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.0.2
  package_info_plus: ^8.1.1
  dialog_flowtter: 
  flutter_facebook_auth: ^7.1.1
  chewie: ^1.8.5
  auto_scroll: ^0.2.0
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  file_picker: ^8.1.6
  excel: ^4.0.6
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.0.0
  csv: ^6.0.0
  flutter_email_sender: ^6.0.3
  
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  mailer: ^6.4.1
  cached_network_image: ^3.4.1
  timezone: ^0.10.0
  
  sign_in_with_apple: ^7.0.1
  paystack_for_flutter: ^1.0.4
 
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  image_cropper: ^9.1.0
  camera: ^0.10.5
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_icons:
  android: true
  ios: true
  image_path: "images/okayappicon3.png" # Path to your app icon
  android_display_name: "Tremsol"
  ios_display_name: "Tremsol"

flutter_native_splash:
  color: "#ffffff" # Background color
  image: images/okayappicon3.png # Your splash image
  android: true
  ios: true


flutter:
  assets:
    - images/jobs.jpg
    - images/games.jpg
    - images/movies.jpg
    - images/fashion.jpg
    - assets/dialog_flow_auth.json
    - assets/google_icon.png
    - assets/logo.png
    - assets/facebook_icon.png
    - assets/apple_icon.png
    - assets/logoappbar.png
 

  uses-material-design: true

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700